version: "3.8"

services:
  date-annotator:
    image: nlpsandbox/date-annotator-example:0.3.2
    build:
      context: server
      dockerfile: Dockerfile
    container_name: date-annotator
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/healthCheck
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"
