blank_issues_enabled: false
contact_links:
- name: NLP Sandbox Discord Server
  url: https://discord.com/invite/Zb4ymtF
  about: |
    Join the NLP Sandbox Team and community and post your question to the
    channel that best matches the topic of your request.
- name: NLP Sandbox Synapse Discussion Forum
  url: https://www.synapse.org/#!Synapse:syn22277123/discussion/default
  about: Please ask questions about submissions and Synapse.